services:
  db:
    image: postgres:18.2
    environment:
      POSTGRES_DB: socialfollia
      POSTGRES_USER: socialfolliauser
      POSTGRES_PASSWORD: socialfolliapass
    ports:
      - "5434:5432"
    networks:
      - private-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    networks:
      - public-network
      - private-network
  api-dev:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8080"
    environment:
      QUARKUS_PROFILE: docker
    networks:
      - public-network
      - private-network
  api-qa:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8082:8080"
    environment:
      QUARKUS_PROFILE: docker
    networks:
      - public-network
      - private-network
networks:
  public-network:
  private-network: