quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=socialfolliauser
quarkus.datasource.password=socialfolliapass

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/socialfollia
quarkus.datasource.jdbc.max-size=16