quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/socialfollia
quarkus.datasource.jdbc.max-size=16

quarkus.http.port=8083

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=socialfolliauser
quarkus.datasource.password=socialfolliapass

# Props do Hibernate para visualizar logs das requisições
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
#quarkus.log.category."org.hibernate.SQL".level=INFO
#quarkus.log.category."org.hibernate.orm.jdbc.bind".level=INFO
#quarkus.log.category."org.hibernate.orm.jdbc.bind".min-level=TRACE
#quarkus.log.category."org.hibernate.orm.jdbc.bind".level=TRACE

# Swagger
quarkus.swagger-ui.always-include=true

# Flyway para Migration DB
quarkus.flyway.migrate-at-start=true